apiVersion: v1
kind: Service
metadata:
  name: platformnpservice-srv
spec:
  type: NodePort
  selector: 
    app: PlatformsService
  ports:
    - name: PlatformsService
      protocol: TCP
      port: 80
      targetPort: 80